"""Scrubbing on the customer's machine: identical tokens to AgentCompile's server (shared
vectors, generated by the server's own scrubber), applied to captured calls before sending."""

from __future__ import annotations

import json
import os
import stat
from pathlib import Path
from typing import Any

import httpx
import openai
import pytest

import agentcompile
from agentcompile import _capture, _scrub

VECTORS = json.loads((Path(__file__).parent / "data" / "scrub-vectors.json").read_text())
KEY = VECTORS["key"].encode()


@pytest.mark.parametrize("case", VECTORS["text"], ids=lambda c: c["input"][:30])
def test_text_matches_the_server(case: dict[str, Any]) -> None:
    assert _scrub.scrub_text(case["input"], KEY) == case["output"]


@pytest.mark.parametrize("case", VECTORS["value"], ids=lambda c: str(c["input"])[:30])
def test_values_match_the_server(case: dict[str, Any]) -> None:
    assert _scrub.scrub_value(case["input"], KEY) == case["output"]


@pytest.mark.parametrize("case", VECTORS["tool_output"], ids=lambda c: c["input"][:30])
def test_tool_outputs_match_the_server(case: dict[str, Any]) -> None:
    assert _scrub.scrub_tool_output(case["input"], KEY) == case["output"]


def test_the_key_comes_from_the_environment(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("AGENTCOMPILE_SCRUB_KEY", "fleet-key")
    assert _scrub.load_key() == b"fleet-key"


def test_otherwise_a_key_is_created_once_owner_only(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.delenv("AGENTCOMPILE_SCRUB_KEY", raising=False)
    monkeypatch.setenv("AGENTCOMPILE_HOME", str(tmp_path))
    first = _scrub.load_key()
    assert len(first) == 64 and _scrub.load_key() == first
    mode = os.stat(tmp_path / "scrub.key").st_mode
    assert stat.S_IMODE(mode) == 0o600


MESSAGES = [
    {"role": "user", "content": "I'm mia@example.com, card 4111 1111 1111 1111"},
    {
        "role": "assistant",
        "content": None,
        "tool_calls": [
            {
                "id": "t1",
                "type": "function",
                "function": {"name": "find_user", "arguments": '{"email": "mia@example.com"}'},
            }
        ],
    },
    {
        "role": "tool",
        "tool_call_id": "t1",
        "content": '{"user_id": "u1", "phone": "415-555-0199"}',
    },
]


class Service:
    def __init__(self) -> None:
        self.sent: list[dict[str, Any]] = []

    def __call__(self, request: httpx.Request) -> httpx.Response:
        if request.url.path == "/v1/capture":
            self.sent += json.loads(request.content)["exchanges"]
            return httpx.Response(200, json={})
        return httpx.Response(200, json={"action": "forward", "reason": "x"})


def _send(scrub: bool, monkeypatch: pytest.MonkeyPatch) -> list[dict[str, Any]]:
    monkeypatch.setenv("AGENTCOMPILE_SCRUB_KEY", VECTORS["key"])
    service = Service()
    completion = {
        "id": "c1",
        "object": "chat.completion",
        "created": 0,
        "model": "m",
        "choices": [
            {
                "index": 0,
                "message": {"role": "assistant", "content": "Done, mia@example.com"},
                "finish_reason": "stop",
            }
        ],
    }
    provider = openai.OpenAI(
        api_key="sk",
        base_url="http://provider.test/v1",
        http_client=httpx.Client(
            transport=httpx.MockTransport(lambda r: httpx.Response(200, json=completion))
        ),
    )
    client = agentcompile.wrap(
        provider,
        base_url="http://ac.test",
        trail=False,
        capture=True,
        scrub=scrub,
        http_client=httpx.Client(transport=httpx.MockTransport(service)),
    )
    client.chat.completions.create(model="m", messages=MESSAGES, conversation_id="c1")
    agentcompile.flush(5)
    _capture._ALL.clear()
    return service.sent


def test_captured_calls_leave_the_machine_scrubbed(monkeypatch: pytest.MonkeyPatch) -> None:
    [record] = _send(True, monkeypatch)
    sent = json.dumps(record)
    assert "mia@example.com" not in sent
    assert "4111 1111 1111 1111" not in sent and "415-555-0199" not in sent
    email = _scrub.scrub_text("mia@example.com", KEY)
    messages = record["request"]["messages"]
    assert email in messages[0]["content"]
    args = json.loads(messages[1]["tool_calls"][0]["function"]["arguments"])
    assert args == {"email": email}  # the same token in what was said and what was passed
    assert json.loads(messages[2]["content"])["user_id"] == "u1"  # ids untouched
    assert email in record["response"]["choices"][0]["message"]["content"]
    assert record["scrubbed"] is True


def test_scrub_false_sends_calls_as_they_are(monkeypatch: pytest.MonkeyPatch) -> None:
    [record] = _send(False, monkeypatch)
    assert "mia@example.com" in json.dumps(record) and "scrubbed" not in record
